/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author REFIKA
 */
public class AbilityCard extends javax.swing.JPanel {

    /**
     * Creates new form AbilityCard
     */
    public AbilityCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AbilityName = new javax.swing.JLabel();
        AbilityDesc = new javax.swing.JLabel();
        AbilityGen = new javax.swing.JLabel();

        setBackground(new java.awt.Color(29, 32, 38));

        AbilityName.setForeground(new java.awt.Color(255, 255, 255));
        AbilityName.setText("name");

        AbilityDesc.setForeground(new java.awt.Color(255, 255, 255));
        AbilityDesc.setText("Desc");

        AbilityGen.setForeground(new java.awt.Color(255, 255, 255));
        AbilityGen.setText("Gen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(AbilityName)
                .addGap(44, 44, 44)
                .addComponent(AbilityGen)
                .addGap(56, 56, 56)
                .addComponent(AbilityDesc)
                .addContainerGap(565, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AbilityName)
                    .addComponent(AbilityDesc)
                    .addComponent(AbilityGen))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setAbility(PokemonData data) {
        initComponents();

        AbilityName.setText(data.ability);
        AbilityGen.setText(String.valueOf(data.abilityGen));
        AbilityDesc.setText(data.abilityDesc);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AbilityDesc;
    private javax.swing.JLabel AbilityGen;
    private javax.swing.JLabel AbilityName;
    // End of variables declaration//GEN-END:variables
}
