/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import javax.swing.BoxLayout;

/**
 *
 * @author REFIKA
 */
public class MoveDex extends javax.swing.JPanel {

    /**
     * Creates new form MoveDex
     */
    MoveData[] data_move = MoveLoader.loadAll();

    public MoveDex() {
        initComponents();
        filterData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jsMoveDex = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        LogoText = new javax.swing.JLabel();
        Type = new javax.swing.JLabel();
        CBType = new javax.swing.JComboBox<>();
        SearchField = new javax.swing.JTextField();
        ScNameField = new javax.swing.JLabel();
        MoveOption = new javax.swing.JScrollPane();
        PanelMove = new javax.swing.JPanel();
        CBCategory = new javax.swing.JComboBox<>();
        CategoryText = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(29, 32, 38));

        LogoText.setFont(new java.awt.Font("Pokemon Solid", 0, 59)); // NOI18N
        LogoText.setForeground(new java.awt.Color(255, 255, 255));
        LogoText.setText("MoveDex");

        Type.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Type.setForeground(new java.awt.Color(255, 255, 255));
        Type.setText("Type:");

        CBType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Type", "Normal ", "Fire ", "Water ", "Electric ", "Grass ", "Ice ", "Fighting ", "Poison ", "Ground ", "Flying ", "Psychic ", "Bug ", "Rock ", "Ghost ", "Dragon ", "Dark ", "Steel ", "Fairy" }));
        CBType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBTypeActionPerformed(evt);
            }
        });

        SearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFieldActionPerformed(evt);
            }
        });

        ScNameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ScNameField.setForeground(new java.awt.Color(255, 255, 255));
        ScNameField.setText("Name:");

        javax.swing.GroupLayout PanelMoveLayout = new javax.swing.GroupLayout(PanelMove);
        PanelMove.setLayout(PanelMoveLayout);
        PanelMoveLayout.setHorizontalGroup(
            PanelMoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1061, Short.MAX_VALUE)
        );
        PanelMoveLayout.setVerticalGroup(
            PanelMoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 808, Short.MAX_VALUE)
        );

        MoveOption.setViewportView(PanelMove);

        CBCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All ", "Physical", "Special", "Status" }));
        CBCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBCategoryActionPerformed(evt);
            }
        });

        CategoryText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CategoryText.setForeground(new java.awt.Color(255, 255, 255));
        CategoryText.setText("Category:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CategoryText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CBCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ScNameField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Type)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CBType, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(429, 429, 429)
                .addComponent(LogoText)
                .addContainerGap(449, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MoveOption, javax.swing.GroupLayout.PREFERRED_SIZE, 1063, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(LogoText)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CategoryText)
                        .addComponent(CBCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ScNameField)
                        .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Type)
                        .addComponent(CBType, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MoveOption, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jsMoveDex.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsMoveDex, javax.swing.GroupLayout.DEFAULT_SIZE, 1141, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsMoveDex, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void filterData() {
        String keyword = SearchField.getText().trim().toLowerCase();
        String selectedType = CBType.getSelectedItem().toString().trim();

        PanelMove.removeAll();
        PanelMove.setLayout(new BoxLayout(PanelMove, BoxLayout.Y_AXIS));

        for (MoveData move : data_move) {
            boolean matchName = move.move != null && move.move.toLowerCase().contains(keyword);
            boolean matchID = String.valueOf(move.moveId).contains(keyword);
            boolean matchType = selectedType.equals("All Type") || (move.type != null && move.type.toLowerCase().contains(selectedType.toLowerCase()));

            if ((matchName || matchID) && matchType) {
                MoveCard card = new MoveCard(
                    move,
                    selectedMove -> {
                        SnorDexPage1.instance.showMoveDetail(selectedMove);
                    }
                );
                card.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, card.getPreferredSize().height));
                PanelMove.add(card);
                PanelMove.add(javax.swing.Box.createVerticalStrut(5));
            }
        }
    }

    private void SearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFieldActionPerformed
        filterData();
    }//GEN-LAST:event_SearchFieldActionPerformed

    private void CBTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBTypeActionPerformed
        filterData();
    }//GEN-LAST:event_CBTypeActionPerformed

    private void CBCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBCategoryActionPerformed
        filterData();
    }//GEN-LAST:event_CBCategoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBCategory;
    private javax.swing.JComboBox<String> CBType;
    private javax.swing.JLabel CategoryText;
    private javax.swing.JLabel LogoText;
    private javax.swing.JScrollPane MoveOption;
    private javax.swing.JPanel PanelMove;
    private javax.swing.JLabel ScNameField;
    private javax.swing.JTextField SearchField;
    private javax.swing.JLabel Type;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jsMoveDex;
    // End of variables declaration//GEN-END:variables
}
