/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author REFIKA
 */
public class MoveCard extends javax.swing.JPanel {

    public interface CardClickListener {
        void onCardClick(MoveData data);
    }

    private CardClickListener listener;

    /**
     * Creates new form MoveCard
     */
    public MoveCard() {
        initComponents();
    }

    public MoveCard(MoveData data, CardClickListener listener) {
        initComponents();

        // Format moveId if numeric, otherwise show raw string
        String idText = "";
        try {
            int idNum = Integer.parseInt(data.moveId);
            idText = String.format("#%04d", idNum);
        } catch (Exception ex) {
            idText = data.moveId != null ? ("#" + data.moveId) : "#-";
        }
        MoveID.setText(idText);
        MoveName.setText(data.name != null && data.name.english != null ? data.name.english : (data.move != null ? data.move : "Unknown"));
        MoveType.setText(data.type != null ? data.type : "");
        MoveCategory.setText(data.category != null ? data.category : "");
        MovePower.setText(data.power != null ? data.power : "");
        MovePP.setText(data.pp != null ? data.pp : "");
        MoveAcc.setText(data.accuracy != null ? data.accuracy : "");

        this.listener = listener;
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        this.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (MoveCard.this.listener != null) {
                    MoveCard.this.listener.onCardClick(data);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MoveID = new javax.swing.JLabel();
        MoveName = new javax.swing.JLabel();
        MoveType = new javax.swing.JLabel();
        MoveCategory = new javax.swing.JLabel();
        MovePower = new javax.swing.JLabel();
        MovePP = new javax.swing.JLabel();
        MoveAcc = new javax.swing.JLabel();

        setBackground(new java.awt.Color(29, 32, 38));

        MoveID.setForeground(new java.awt.Color(255, 255, 255));
        MoveID.setText("ID");

        MoveName.setForeground(new java.awt.Color(255, 255, 255));
        MoveName.setText("Name");

        MoveType.setForeground(new java.awt.Color(255, 255, 255));
        MoveType.setText("Type");

        MoveCategory.setForeground(new java.awt.Color(255, 255, 255));
        MoveCategory.setText("Move Cat");

        MovePower.setForeground(new java.awt.Color(255, 255, 255));
        MovePower.setText("Power");

        MovePP.setForeground(new java.awt.Color(255, 255, 255));
        MovePP.setText("PP");

        MoveAcc.setForeground(new java.awt.Color(255, 255, 255));
        MoveAcc.setText("Accuracy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(MoveID)
                .addGap(36, 36, 36)
                .addComponent(MoveName)
                .addGap(101, 101, 101)
                .addComponent(MoveType)
                .addGap(104, 104, 104)
                .addComponent(MoveCategory)
                .addGap(110, 110, 110)
                .addComponent(MovePower)
                .addGap(125, 125, 125)
                .addComponent(MovePP)
                .addGap(156, 156, 156)
                .addComponent(MoveAcc)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MoveID)
                    .addComponent(MoveName)
                    .addComponent(MoveType)
                    .addComponent(MoveCategory)
                    .addComponent(MovePower)
                    .addComponent(MovePP)
                    .addComponent(MoveAcc))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MoveAcc;
    private javax.swing.JLabel MoveCategory;
    private javax.swing.JLabel MoveID;
    private javax.swing.JLabel MoveName;
    private javax.swing.JLabel MovePP;
    private javax.swing.JLabel MovePower;
    private javax.swing.JLabel MoveType;
    // End of variables declaration//GEN-END:variables
}
