/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author REFIKA
 */
public class PokeDetail extends javax.swing.JPanel {

    /**
     * Creates new form PokeDetail
     */
    public PokeDetail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSPokeDetail = new javax.swing.JScrollPane();
        PokeDetailJp = new javax.swing.JPanel();
        PokeName = new javax.swing.JLabel();

        PokeDetailJp.setBackground(new java.awt.Color(29, 32, 38));

        PokeName.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        PokeName.setForeground(new java.awt.Color(255, 255, 255));
        PokeName.setText("Pokemon Name");

        javax.swing.GroupLayout PokeDetailJpLayout = new javax.swing.GroupLayout(PokeDetailJp);
        PokeDetailJp.setLayout(PokeDetailJpLayout);
        PokeDetailJpLayout.setHorizontalGroup(
            PokeDetailJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PokeDetailJpLayout.createSequentialGroup()
                .addGap(429, 429, 429)
                .addComponent(PokeName)
                .addContainerGap(673, Short.MAX_VALUE))
        );
        PokeDetailJpLayout.setVerticalGroup(
            PokeDetailJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PokeDetailJpLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(PokeName)
                .addContainerGap(982, Short.MAX_VALUE))
        );

        jSPokeDetail.setViewportView(PokeDetailJp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSPokeDetail, javax.swing.GroupLayout.DEFAULT_SIZE, 1129, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSPokeDetail, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PokeDetailJp;
    private javax.swing.JLabel PokeName;
    private javax.swing.JScrollPane jSPokeDetail;
    // End of variables declaration//GEN-END:variables
}
