/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import javax.swing.*;

/**
 *
 * @author REFIKA
 */
public class Pokedex extends javax.swing.JPanel {

    PokemonData[] data_pokemon = PokemonLoader.loadAll();

    /**
     * Creates new form Pokedex
     */
    public Pokedex() {
        initComponents();

        tampilKanData();

        SearchField.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e)  { filterData(); }
            public void removeUpdate(javax.swing.event.DocumentEvent e)  { filterData(); }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { filterData(); }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPokedexPanel = new javax.swing.JScrollPane();
        PokedexPanel = new javax.swing.JPanel();
        MainLogo = new javax.swing.JLabel();
        SearchField = new javax.swing.JTextField();
        ScNameField = new javax.swing.JLabel();
        Type = new javax.swing.JLabel();
        CBType = new javax.swing.JComboBox<>();
        PokemonCardJS = new javax.swing.JScrollPane();
        PanelData = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(1636, 1080));
        setPreferredSize(new java.awt.Dimension(1636, 1080));

        PokedexPanel.setBackground(new java.awt.Color(29, 32, 38));

        MainLogo.setFont(new java.awt.Font("Pokemon Solid", 1, 59)); // NOI18N
        MainLogo.setForeground(new java.awt.Color(255, 255, 255));
        MainLogo.setText("Pokédex");

        SearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFieldActionPerformed(evt);
            }
        });

        ScNameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ScNameField.setForeground(new java.awt.Color(255, 255, 255));
        ScNameField.setText("Name:");

        Type.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Type.setForeground(new java.awt.Color(255, 255, 255));
        Type.setText("Type:");

        CBType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Type", "Normal ", "Fire ", "Water ", "Electric ", "Grass ", "Ice ", "Fighting ", "Poison ", "Ground ", "Flying ", "Psychic ", "Bug ", "Rock ", "Ghost ", "Dragon ", "Dark ", "Steel ", "Fairy" }));
        CBType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDataLayout = new javax.swing.GroupLayout(PanelData);
        PanelData.setLayout(PanelDataLayout);
        PanelDataLayout.setHorizontalGroup(
            PanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1092, Short.MAX_VALUE)
        );
        PanelDataLayout.setVerticalGroup(
            PanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 791, Short.MAX_VALUE)
        );

        PokemonCardJS.setViewportView(PanelData);

        javax.swing.GroupLayout PokedexPanelLayout = new javax.swing.GroupLayout(PokedexPanel);
        PokedexPanel.setLayout(PokedexPanelLayout);
        PokedexPanelLayout.setHorizontalGroup(
            PokedexPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PokedexPanelLayout.createSequentialGroup()
                .addGroup(PokedexPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PokedexPanelLayout.createSequentialGroup()
                        .addGap(441, 441, 441)
                        .addComponent(MainLogo))
                    .addGroup(PokedexPanelLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(ScNameField)
                        .addGap(18, 18, 18)
                        .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(Type)
                        .addGap(18, 18, 18)
                        .addComponent(CBType, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PokedexPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(PokemonCardJS, javax.swing.GroupLayout.PREFERRED_SIZE, 1094, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        PokedexPanelLayout.setVerticalGroup(
            PokedexPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PokedexPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(MainLogo)
                .addGap(36, 36, 36)
                .addGroup(PokedexPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScNameField)
                    .addComponent(Type)
                    .addComponent(CBType, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(PokemonCardJS, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        MainPokedexPanel.setViewportView(PokedexPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPokedexPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1141, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPokedexPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CBTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBTypeActionPerformed
        filterData();
    }//GEN-LAST:event_CBTypeActionPerformed

    private void SearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFieldActionPerformed
        filterData();
    }//GEN-LAST:event_SearchFieldActionPerformed

    private void tampilKanData() {
        PanelData.removeAll();
        PanelData.setLayout(new BoxLayout(PanelData, BoxLayout.Y_AXIS));

        for (PokemonData poke : data_pokemon ) {
            PokemonCard namaPoke = new PokemonCard(poke);
            namaPoke.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, namaPoke.getPreferredSize().height));
            PanelData.add(namaPoke);
            PanelData.add(javax.swing.Box.createVerticalStrut(5));
        }
        PanelData.revalidate();
        PanelData.repaint();
    }

    private void filterData() {
        String keyword = SearchField.getText().trim().toLowerCase();
        String selectedType = CBType.getSelectedItem().toString().trim();

        PanelData.removeAll();
        PanelData.setLayout(new BoxLayout(PanelData, BoxLayout.Y_AXIS));

        for (PokemonData poke : data_pokemon) {
            boolean matchName = poke.name.toLowerCase().contains(keyword);
            boolean matchID = String.valueOf(poke.id).contains(keyword);
            boolean matchType = selectedType.equals("All Type") || poke.types.toLowerCase().contains(selectedType.toLowerCase());

            if ((matchName || matchID) && matchType) {
                PokemonCard card = new PokemonCard(poke);
                card.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, card.getPreferredSize().height));
                PanelData.add(card);
                PanelData.add(javax.swing.Box.createVerticalStrut(5));
            }
        }

        PanelData.revalidate();
        PanelData.repaint();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBType;
    private javax.swing.JLabel MainLogo;
    private javax.swing.JScrollPane MainPokedexPanel;
    private javax.swing.JPanel PanelData;
    private javax.swing.JPanel PokedexPanel;
    private javax.swing.JScrollPane PokemonCardJS;
    private javax.swing.JLabel ScNameField;
    private javax.swing.JTextField SearchField;
    private javax.swing.JLabel Type;
    // End of variables declaration//GEN-END:variables
}
