/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import java.awt.*;

/**
 *
 * @author REFIKA
 */
public class PokemonCard extends javax.swing.JPanel {

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents

    public interface CardClickListener {
        void onCardClick(PokemonData data);
    }

    private CardClickListener listener;

    private void initComponents() {

        PokeBall = new javax.swing.JPanel();
        ID = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        TypeLabel = new javax.swing.JLabel();
        TTotal = new javax.swing.JLabel();
        THP = new javax.swing.JLabel();
        TDef = new javax.swing.JLabel();
        TAtk = new javax.swing.JLabel();
        TSpA = new javax.swing.JLabel();
        TSpD = new javax.swing.JLabel();
        TSpe = new javax.swing.JLabel();
        jLTotal = new javax.swing.JLabel();
        jLHP = new javax.swing.JLabel();
        jLDef = new javax.swing.JLabel();
        jLAtk = new javax.swing.JLabel();
        jLSpA = new javax.swing.JLabel();
        jLSpD = new javax.swing.JLabel();
        jLSpe = new javax.swing.JLabel();

        setBackground(new java.awt.Color(38, 58, 74));

        PokeBall.setBackground(new java.awt.Color(38, 58, 74));

        javax.swing.GroupLayout PokeBallLayout = new javax.swing.GroupLayout(PokeBall);
        PokeBall.setLayout(PokeBallLayout);
        PokeBallLayout.setHorizontalGroup(
            PokeBallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        PokeBallLayout.setVerticalGroup(
            PokeBallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 111, Short.MAX_VALUE)
        );

        ID.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        ID.setForeground(new java.awt.Color(255, 255, 255));
        ID.setText("ID");

        Name.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Name");

        TypeLabel.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        TypeLabel.setForeground(new java.awt.Color(255, 255, 255));
        TypeLabel.setText("Type/Type");

        TTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TTotal.setForeground(new java.awt.Color(255, 255, 255));
        TTotal.setText("Total");

        THP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        THP.setForeground(new java.awt.Color(255, 255, 255));
        THP.setText("HP");

        TDef.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TDef.setForeground(new java.awt.Color(255, 255, 255));
        TDef.setText("Def");

        TAtk.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TAtk.setForeground(new java.awt.Color(255, 255, 255));
        TAtk.setText("Atk");

        TSpA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TSpA.setForeground(new java.awt.Color(255, 255, 255));
        TSpA.setText("Sp.A");

        TSpD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TSpD.setForeground(new java.awt.Color(255, 255, 255));
        TSpD.setText("Sp.D");

        TSpe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TSpe.setForeground(new java.awt.Color(255, 255, 255));
        TSpe.setText("Spe");

        jLTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLTotal.setForeground(new java.awt.Color(255, 255, 255));
        jLTotal.setText("Total");

        jLHP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLHP.setForeground(new java.awt.Color(255, 255, 255));
        jLHP.setText("HP");

        jLDef.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLDef.setForeground(new java.awt.Color(255, 255, 255));
        jLDef.setText("Def");

        jLAtk.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLAtk.setForeground(new java.awt.Color(255, 255, 255));
        jLAtk.setText("Atk");

        jLSpA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLSpA.setForeground(new java.awt.Color(255, 255, 255));
        jLSpA.setText("Sp.A");

        jLSpD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLSpD.setForeground(new java.awt.Color(255, 255, 255));
        jLSpD.setText("Sp.D");

        jLSpe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLSpe.setForeground(new java.awt.Color(255, 255, 255));
        jLSpe.setText("Spe");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PokeBall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ID)
                .addGap(77, 77, 77)
                .addComponent(Name)
                .addGap(136, 136, 136)
                .addComponent(TypeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TTotal)
                        .addGap(95, 95, 95)
                        .addComponent(THP)
                        .addGap(18, 18, 18)
                        .addComponent(TAtk)
                        .addGap(18, 18, 18)
                        .addComponent(TDef)
                        .addGap(18, 18, 18)
                        .addComponent(TSpA)
                        .addGap(18, 18, 18)
                        .addComponent(TSpD)
                        .addGap(18, 18, 18)
                        .addComponent(TSpe))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLTotal)
                        .addGap(95, 95, 95)
                        .addComponent(jLHP)
                        .addGap(18, 18, 18)
                        .addComponent(jLAtk)
                        .addGap(18, 18, 18)
                        .addComponent(jLDef)
                        .addGap(18, 18, 18)
                        .addComponent(jLSpA)
                        .addGap(18, 18, 18)
                        .addComponent(jLSpD)
                        .addGap(18, 18, 18)
                        .addComponent(jLSpe)))
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PokeBall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID)
                    .addComponent(Name)
                    .addComponent(TypeLabel)))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TTotal)
                    .addComponent(THP)
                    .addComponent(TAtk)
                    .addComponent(TDef)
                    .addComponent(TSpA)
                    .addComponent(TSpD)
                    .addComponent(TSpe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTotal)
                    .addComponent(jLHP)
                    .addComponent(jLAtk)
                    .addComponent(jLDef)
                    .addComponent(jLSpA)
                    .addComponent(jLSpD)
                    .addComponent(jLSpe)))
        );
    }// </editor-fold>//GEN-END:initComponents

    public PokemonCard(PokemonData data, CardClickListener listener) {
        initComponents();

        ID.setText("#" + String.format("%04d", data.id));
        Name.setText(data.name);
        TypeLabel.setText(data.primaryTypes + "/" + data.secondaryTypes);

        TTotal.setText("Total"); // header tetap
        THP.setText("HP");
        TAtk.setText("Atk");
        TDef.setText("Def");
        TSpA.setText("Sp.A");
        TSpD.setText("Sp.D");
        TSpe.setText("Spe");

        jLTotal.setText(String.valueOf(data.total));
        jLHP.setText(String.valueOf(data.hp));
        jLAtk.setText(String.valueOf(data.atk));
        jLDef.setText(String.valueOf(data.def));
        jLSpA.setText(String.valueOf(data.spA));
        jLSpD.setText(String.valueOf(data.spD));
        jLSpe.setText(String.valueOf(data.spe));

        this.setCursor(new java.awt.Cursor(Cursor.HAND_CURSOR));
        this.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (listener != null) {
                    listener.onCardClick(data);
                }
            }
        });

        this.listener = listener;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JLabel Name;
    private javax.swing.JPanel PokeBall;
    private javax.swing.JLabel TAtk;
    private javax.swing.JLabel TDef;
    private javax.swing.JLabel THP;
    private javax.swing.JLabel TSpA;
    private javax.swing.JLabel TSpD;
    private javax.swing.JLabel TSpe;
    private javax.swing.JLabel TTotal;
    private javax.swing.JLabel TypeLabel;
    private javax.swing.JLabel jLAtk;
    private javax.swing.JLabel jLDef;
    private javax.swing.JLabel jLHP;
    private javax.swing.JLabel jLSpA;
    private javax.swing.JLabel jLSpD;
    private javax.swing.JLabel jLSpe;
    private javax.swing.JLabel jLTotal;
    // End of variables declaration//GEN-END:variables
}
